export const ERROR_CODES = {
    BAD_REQUEST: "BAD_REQUEST",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    CONFLICT: "CONFLICT",
    VALIDATION_FAILED: "VALIDATION_FAILED",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    TOO_MANY_REQUEST: "TOO_MANY_REQUEST",
    ZOD_VALIDATION_ERROR: "ZOD_VALIDATION_ERROR"
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES]